project:
  type: website

website:
  title: "The Null Hypothesis"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ds-ramakant
      - icon: linkedin
        href: https://www.linkedin.com/in/dsramakant/
  google-analytics: 'G-T5T39KBDW1'
  
format:
  html:
    theme: journal
    css: styles.css

editor: visual

