---
title: Keeping it together
author: ''
date: '2022-08-18'
slug: keeping-it-together
categories:
  - personal
tags:
  - private
  - personal
  - blog
subtitle: 'What *really* happens after getting laid off'
summary: 'This is a private post to remind myself of what it feels like'
authors: []
lastmod: '2022-08-18T12:36:34+05:30'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: true
---

# Private post (stop reading!)

Exactly 4 weeks ago, I got laid off from MX Player. I've worked in 3 companies and this is the 2nd company that has laid me off. Fancy strike rate!

The last time I was laid off, the entire India office folded itself. This time however, only a part of the workforce got affected. This led to a lot more heartburn. Friends are still employed in the same company. Inevitably, this leads to vicious swings between self-doubt and denial.

## Why Me?

-   Should I have worked harder? *"But i thought I did everything and more"*
-   Did I play the politics wrong? *"I shouldn't have been so meek. I should have fought harder and been a lot more aggressive"*
-   Could I have prevented this? *"Why did I not see this coming?"*

This happens every few days. The only thing I can do is keep myself distracted. That's my base line right now - **just keep head above water**. No long term plans. No big thoughts. Just do whatever is necessary not to fall back in the abyss.

Its really hard to see a silver lining in all this. I mean, this feeling is not new. I've been in this place before. Multiple times over the last 20 years. My entire adult life has been built on a series of disappointments and second-best alternatives. If I've been unable to observe what good came out of these miseries, then so be it. Its just who I am. I'm just not good enough.

This period is the worst for anyone who's a social media addict. I'm a classic lurker - just browse all day without posting anything. I look at all these pristine perfect images that are projected in the public sphere. And then I think about where I am right now. **38-year old male post graduate with a family to sustain struggling to find a job.** That's me right there. I feel my superpower is that every time I open Linkedin, someone else gets a job! I used to be happy for others but in this period, I fake my congratulations and continue scrolling. Aimlessly looking for other things to feel bad about. This stomach-wrenching sensation is so familiar. Its happened so many times before. And it always hurts. I'm just not good enough.

Isn't it sad how we are always projecting such a immaculate version of ourselves to the larger public? So much care is taken to cover up even the slightest of mistake and appear to be *always winning*! But what to do when you've actually lost? How do you protect yourself from that?

## Moving on? 

Sometimes, I try to look ahead. Not think about the bad stuff and just push myself. The first week was horrible and mentally exhausting. I just refused to think about what happened. Honestly it was the only way I could stop myself from feeling worse. It took around 7 days for me to pick up the pieces and start planning on the next steps. Very gradually I started reaching out to few friends and explaining that I'm desperate to find a job.

Today I'm distraught because I've been rejected by Samsung R&D. This was specially painful because I really wanted to into a non-media non-Mumbai company. I was looking forward to starting afresh but it seems my options are going to be severely limited.

None of the MAANG interviews resulted in anything. Whatever they see me as, is not a fit for them. Have no idea how to correct this and at this time in my career I think it may be too late.

## What is my future? 

I've got three distinct phases in my career

1.  Broadcast experience @ Sony
2.  Growth marketing experience @ Viu
3.  Content Analysis @ MX

There's one part of me that tells me to pursue data science. But I know I suck at it. So I'm possibly going to have to settle for just some kind of strategy related role. Neither budget facing nor market facing. Irrespective of whether I was laid off or not, the entire tenure at MX has been extremely non-productive to my career. I found some joy in the last few weeks after joining the Data team but that dream died instantly.

The one active conversation that is open right now is with JioTV. It will be a Content role to drive acquisition/partnership. Sigh! Another compromise. Exactly the way it was with MX! I have no energy for this disappointment. I'd rather just go with the flow and see where this goes. Got no clue about long term career so I might as well give it up.

## Running as a way of coping

The only thing that I feel good about. Waking up and running. Its my way of feeling confident. I still smoke and wish I didn't. 2-3 times in a week I wake up early and sweat it out for 45 minutes. That's one way to shake up the body and "feel good". The plan is to aim for the 21k in Jan'23. Don't want to go wrong with that. My only silver lining from 2022.

## What they don't tell you about 

-   Check your finances immediately. I removed all market facing instruments and stuffed my monthly SIP into fixed deposits. With a volatile market, its always good to shore up some funds for the short-term (3-6 month horizon)
-   Watch out for your mental health. The signs are easy to spot. Do whatever it takes to stop being unhappy. By not addressing the sadness and letting it fester you are harming yourself and those around you. Realise that you are feeling sad and try to distract yourself immediately.
-   Focus on small things that make you feel happy
    -   I take pleasure in my vinyl collection. So I figured that this would be the only time to clean the old records and digitise them for further use.
-   Learn a new skill. Keep that brain sharp. Pick up a challenge to keep the fight alive in you!
