---
title: "Day 14 of #50daysofKaggle"
subtitle: "Roadmap to Tidymodels - Part 2"
description: "Screening multiple models"
date: '2023-03-04'
categories: [R, kaggle]
featured: no
execute:
  warning: false
---

Today's post is an attempt to use the `tidymodels` framework to screen multiple models. Inspiration for this post comes from the [Ch 15 of the Tidymodels with R textbook](https://www.tmwr.org/workflow-sets.html) along with two more noteworthy blogs

-   [Olivier Gimenez's post](https://oliviergimenez.github.io/blog/learning-machine-learning/) that had me marvelling at the feature engineering
-   [Tural Sadigov's post](https://rpubs.com/tsadigov/titanic_tidymodels) on handling multiple models

But first a clarification ...

# What's with the numbering of these posts? 

Day 8, Day 11 and now Day 14.. what happened to all the days in between?

And ... what does #50daysofKaggle even supposed to mean?

Attempting a kaggle competition has been one of the longest running aspiration for me. Exactly 6 years ago in March '17, I created my profile. At that time, I was pretty sure I had it in me to get cracking. But I knew I had to start learning to code. So I just kept learning... and learning... and learning... without any real application. As with any new project, I think I may have spent way too much time in planning and worrying about stuff instead of actually ... doing stuff!

Many false starts later, it was in the winter of 2022 I had to take that hard decision.

#50daysofkaggle was my own personal challenge to check-in daily here to ensure that I'm giving at least 50 consecutive days to my worst fears. My [first kaggle post](https://www.ds-ramakant.com/posts/2022-10-07-day-1-of-50daysofkaggle/index.en.html) was on 7th Oct. Its roughly 150 days since then. Here are my thoughts so far:

1.  the first post was using Python. Now I'm attempting tidymodels using R. In a way, I'm happy to be learning while trying to remain language-nuetral. Area of improvement - more Python might be useful!
2.  these posts are taking longer to write than I thought. Seriously... where
